# Generated by Django 4.0.6 on 2023-01-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0006_note_tags_alter_note_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
    ]
